package com.Notepad;

import java.util.Random;
import java.util.Scanner;

public class Game {

    public int startGame() {
        Scanner scanner = new Scanner(System.in);

        int playerResponse = 0;
        boolean again;
        do while (again) {



            {
                again = false;
                System.out.println("Enter a number between 1-3 (1= Rock, 2 = Paper, 3 = Scissors)");
                playerResponse = scanner.nextInt();
                if (!(playerResponse > 0 && playerResponse < 4)) {
                    again = true;
                    scanner.reset();
                }
            }
            while (again) ;

            int cpuResponse = getCPUResonse();
            if (cpuResponse > playerResponse) {
                return cpuResponse;


            } else if (cpuResponse > playerResponse) {
                return playerResponse;
            }
            return 0;


        }


        //start game

        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)

        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        public int getCPUResonse (); {
            Random random = new Random();
            return random.nextInt(3) + 1;
        }

    }


















